all:
	g++ fft_run.cpp -isystem /home/a2hirani/tbb41_20130116oss/include/ -L/home/a2hirani/tbb41_20130116oss/lib/intel64/cc4.1.0_libc2.4_kernel2.6.16.21/ -ltbb -lrt -Xlinker -rpath -Xlinker /home/a2hirani/tbb41_20130116oss/lib/intel64/cc4.1.0_libc2.4_kernel2.6.16.21/

